name: Run SGDataDownloader on PR

on:
  pull_request:
    branches:
      - main

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10.9' # Specify the Python version you are using

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install certifi==2024.6.2 charset-normalizer==3.3.2 idna==3.7 libsql-experimental==0.0.34 requests==2.32.3 urllib3==2.2.1

    - name: Run SGDataDownloader/main.py
      run: python SGDataDownloader/main.py
